// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrpwOFFSRQJNHItDugVVmnfTOxznusow',
    appId: '1:820376651642:web:6fcb98a0b188949d1978c3',
    messagingSenderId: '820376651642',
    projectId: 'tripswipe-6df36',
    authDomain: 'tripswipe-6df36.firebaseapp.com',
    storageBucket: 'tripswipe-6df36.appspot.com',
    measurementId: 'G-CDLJ9XE1K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_oYvz_yaN0bCzhOvMp40yrvuecgXbiow',
    appId: '1:820376651642:android:02d8d87887e6bc5b1978c3',
    messagingSenderId: '820376651642',
    projectId: 'tripswipe-6df36',
    storageBucket: 'tripswipe-6df36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmALct86Gr0nNrGYkOho7likrg0Af6Cdw',
    appId: '1:820376651642:ios:f14d3191295f4d111978c3',
    messagingSenderId: '820376651642',
    projectId: 'tripswipe-6df36',
    storageBucket: 'tripswipe-6df36.appspot.com',
    iosBundleId: 'com.example.tripswipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmALct86Gr0nNrGYkOho7likrg0Af6Cdw',
    appId: '1:820376651642:ios:80b3812fbf3e03131978c3',
    messagingSenderId: '820376651642',
    projectId: 'tripswipe-6df36',
    storageBucket: 'tripswipe-6df36.appspot.com',
    iosBundleId: 'com.example.tripswipe.RunnerTests',
  );
}
